export const GET_POKEMONS = 'GET_POKEMONS';
export const GET_POKEMON_DETAILS = 'GET_POKEMON_DETAILS';
export const GET_POKEMONS_BY_NAME = 'GET_POKEMONS_BY_NAME';
export const GET_POKEMONS_TYPES = 'GET_POKEMONS_TYPES';
export const ORDER_POKEMONS_BY_NAME = 'ORDER_POKEMONS_BY_NAME';
export const ORDER_POKEMONS_BY_ATTACK = 'ORDER_POKEMONS_BY_ATTACK';
export const FILTER_POKEMONS = 'FILTER_POKEMONS';
export const CREATE_POKEMON = 'CREATE_POKEMON';
